version: "3.7"

services:
  zookeeper:
    image: zookeeper  
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 192.168.8.113
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9999:9000
    environment:
      ZK_HOSTS: 192.168.8.113:2181