version: "3.7"

services:
    zoo1:
        image: zookeeper
        restart: always
        hostname: zoo1
        container_name: zoo1
        ports: 
            - 2184:2181
        volumes:
            - "./zoo_cluster/zoo1/data:/data"
            - "./zoo_cluster/zool/datalog:/datalog"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
        networks:
            blz0810:
                ipv4_address:172.19.0.11
    
    zoo2:
        image: zookeeper
        restart: always
        hostname: zoo2
        container_name: zoo2
        ports: 
            - 2185:2181
        volumes:
            - "./zoo_cluster/zoo2/data:/data"
            - "./zoo_cluster/zoo2/datalog:/datalog"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo1:2888:3888 server.3=zoo3:2888:3888
        networks:
            blz0810:
                ipv4_address:172.19.0.12
    
    zoo3:
        image: zookeeper
        restart: always
        hostname: zoo3
        container_name: zoo3
        ports: 
            - 2186:2181
        volumes:
            - "./zoo_cluster/zoo3/data:/data"
            - "./zoo_cluster/zoo3/datalog:/datalog"
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo1:2888:3888
        networks:
            blz0810:
                ipv4_address:172.19.0.13
    
networks:
    blz0810:
        external:
            name: blz0810